namespace StaticReflection.CodeGen
{
    internal static class StaticReflectionAttributeConsts
    {
        public static readonly string Name = "StaticReflection.Annotions.StaticReflectionAttribute";

        public static readonly string TypeName = "Type";
    }
    internal static class StaticReflectionAssemblyAttributeConsts
    {
        public static readonly string Name = "StaticReflection.Annotions.StaticReflectionAssemblyAttribute";

        public static readonly string WithDefaultName = "WithDefault";
    }

    internal static class GenHeaders
    {
        public static readonly string Verson = "1.0.0";

        public static readonly string AutoGenHead = "// <auto-generated/>";

        public static readonly string GeneratedCodeAttribute = $"global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"StaticReflection.CodeGen\", \"{Verson}\")";

        public static readonly string DebuggerStepThroughAttribute = "global::System.Diagnostics.DebuggerStepThrough";

        public static readonly string CompilerGeneratedAttribute = "global::System.Runtime.CompilerServices.CompilerGenerated";

        public static readonly string AttackAttribute = $"[{GeneratedCodeAttribute}]\n[{DebuggerStepThroughAttribute}]\n[{CompilerGeneratedAttribute}]";
    }
}
